# NumPy :
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
- NumPy stands for Numerical Python.
- Fast operations on large amounts of numerical data
- Multi-dimensional arrays (like lists but much faster and more efficient)
- Mathematical functions for linear algebra, statistics, random numbers, etc.

In [2]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [2]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

## CREATING ARRAYS : 

In [4]:
my_list = [0,1,2,3,4,5] # this is a python List
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
print(my_list)

[0, 1, 2, 3, 4, 5]


In [6]:
arr = np.array(my_list) # and this is a Numpy Array
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
np.           # gives syntaxError becaouse after dot there is no any function 

SyntaxError: invalid syntax (2469254449.py, line 1)

In [9]:
np.arange(10) # arange() is similar to range(), but arange() creates a  1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3.0) # float array

array([0., 1., 2.])

In [11]:
np.arange(0, 5) # here arange() is also take start,stop and step like range() 

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(20, 10) # must be start > stop , here we give start is smaller than stop

array([], dtype=int64)

In [14]:
np.arange(-20,10) # this will work  

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
np.arange(-20, -10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [17]:
np.arange(30, 20)

array([], dtype=int64)

In [18]:
ar = np.arange(-30,10)

In [19]:
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9])

In [20]:
np.arange(10,10) # only give start > stop

array([], dtype=int64)

In [21]:
np.arange() # here we pass no argument, then it give typeError means atleat one argument must be given

TypeError: arange() requires stop to be specified.

In [22]:
np.arange(10, 30, 5) # here 3 argument is given the last argument is step

array([10, 15, 20, 25])

In [23]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [24]:
np.arange(10,30,5,8) # it cannot take 4 argument

TypeError: Cannot interpret '8' as a data type

In [25]:
np.zeros(3) # parameter Tunning, by default system gives float 

array([0., 0., 0.])

In [26]:
np.zeros(3, dtype = int) # Hyper parameter Tunning, here user changed system's parameter

array([0, 0, 0])

In [29]:
np.zeros((2,2), dtype = int) # 2x2 matrix with integer type

array([[0, 0],
       [0, 0]])

In [31]:
zeros = np.zeros([2,3])
print(zeros)
print(type(zeros))  #ndarray means: n-dimension array
print(zeros.shape)  # it shows matrix's raw and column

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
(2, 3)


In [32]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((10,30)) # 10  raws and 30 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [3]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [4]:
n = (6,7)
n1 = (6,8)

print(np.zeros(n1))  # parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
print(np.zeros(n, dtype = int))  # hyper parameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [6]:
n

(6, 7)

In [7]:
n1

(6, 8)

In [8]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [11]:
print(np.zeros((2,3,4),dtype = int))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [12]:
print(np.zeros((3,3,4),dtype = int))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [13]:
print(np.zeros((3,3,3),dtype = int))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


### Arrays of Ones :

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones(3,dtype = int)

array([1, 1, 1])

In [16]:
n

(6, 7)

In [17]:
n1

(6, 8)

In [18]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.ones((5,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [20]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [21]:
np.twos((2,3)) 

AttributeError: module 'numpy' has no attribute 'twos'

In [22]:
np.thress((3,4))

AttributeError: module 'numpy' has no attribute 'thress'

In [23]:
np.ones(2)

array([1., 1.])

In [24]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.ones((6,10),dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [26]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [27]:
np.threes((4,5))

AttributeError: module 'numpy' has no attribute 'threes'

### range :

In [28]:
range(5)

range(0, 5)

In [29]:
r = range(10)
r

range(0, 10)

In [30]:
for i in r:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [31]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
list(range(1,10,3))

[1, 4, 7]

In [33]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

### random module :
- random is a module we can simply import it
- import random , then random will be imported and dont need to write np.random.rand,  now we can directly use it
- rand() : it will matrix or array values lies between 0 to 1 and every execution values will be change
- randit() : it generates a random integer (whole number) within a specified range.
- randn() : generates random numbers from a standard normal distribution

In [34]:
rand(3,2)

NameError: name 'rand' is not defined

In [35]:
random.rand(3,2) # not proper way to calling it

NameError: name 'random' is not defined

In [36]:
np.random.rand(3,2) # rand() will always give values under 0 to 1

array([[0.54749234, 0.45757781],
       [0.37577736, 0.94788273],
       [0.23806486, 0.67494871]])

In [38]:
np.random.rand(5)

array([0.93356439, 0.14209203, 0.06572437, 0.78384984, 0.69629759])

In [39]:
np.random.rand(4)

array([0.54043194, 0.30390447, 0.70799995, 0.31279986])

In [40]:
np.rand(4) # Wrong way to callig it

AttributeError: module 'numpy' has no attribute 'rand'

In [42]:
np.random.rand(2,4) # 2x4 matrix values lies between 0 to 1

array([[0.19317402, 0.9119154 , 0.63864379, 0.23433651],
       [0.09435158, 0.87260463, 0.28977761, 0.19144974]])

### randint() :


In [45]:
np.random.randint((2,10))

array([1, 5], dtype=int32)

In [46]:
np.random.randint(0,1) 

0

In [3]:
np.random.randint(2,20)  #high(2nd argument) exclusive

13

In [4]:
np.random.randint(10,20,5) # here 5 is a size 

array([14, 13, 14, 11, 11], dtype=int32)

In [5]:
np.random.randint(10,30,size=16)

array([26, 22, 28, 12, 12, 15, 16, 19, 18, 11, 12, 12, 11, 21, 28, 11],
      dtype=int32)

In [6]:
np.random.randint(1,6,4)

array([3, 2, 5, 1], dtype=int32)

In [7]:
np.random.rand(3)

array([0.56938388, 0.03430427, 0.94397971])

In [8]:
np.random.randint(1)

0

In [9]:
np.random.randint(30,20,5) # low must be less than equal to high

ValueError: low >= high

In [10]:
np.random.randint(-30,20,10)

array([  3, -28,  17,  13,  -9, -11, -30,  -9,  -4, -15], dtype=int32)

In [11]:
np.random.randint(20,30,10)

array([24, 23, 27, 26, 28, 21, 24, 28, 25, 23], dtype=int32)

In [12]:
np.random.randint(5,9) # if we dont give any size then by default it considered as size = 1

5

In [13]:
np.random.randint(1,12,10)

array([ 5,  2, 10,  1, 11,  7, 11,  8,  3,  8], dtype=int32)

In [14]:
np.random.randint(10,40,(10,10)) # here size = (10,10) means 10x10 matrix

array([[11, 23, 20, 16, 13, 11, 34, 34, 19, 10],
       [31, 37, 20, 20, 29, 11, 26, 18, 17, 33],
       [31, 16, 19, 19, 19, 38, 20, 17, 29, 23],
       [34, 38, 21, 33, 12, 26, 10, 26, 36, 27],
       [20, 35, 29, 38, 18, 25, 16, 31, 31, 35],
       [23, 33, 29, 14, 31, 10, 23, 10, 31, 32],
       [24, 31, 37, 27, 36, 37, 34, 33, 20, 14],
       [36, 20, 38, 21, 34, 35, 23, 28, 11, 21],
       [35, 12, 20, 28, 27, 11, 15, 23, 16, 16],
       [18, 15, 11, 21, 31, 12, 22, 38, 18, 13]], dtype=int32)

In [15]:
np.random.randint(1,100,(12,12))

array([[89, 93, 54, 60, 37, 89, 46, 31, 58, 35, 98, 79],
       [47, 58, 24, 47, 99, 14, 86, 21, 56, 59, 11, 79],
       [72, 53, 47, 29, 55, 66, 26, 24, 76,  2, 29, 51],
       [33, 65,  7, 25, 68, 19, 44, 98, 83,  5, 51, 97],
       [78, 38, 18, 38, 61, 91, 45, 19, 43, 93, 70, 79],
       [11, 13, 95, 60,  3, 45, 23, 20,  7, 19, 78, 47],
       [85, 78, 37, 29, 88, 30, 66, 22, 12, 61, 25, 83],
       [86, 47,  8, 54, 64, 87, 75, 30, 23, 71, 52, 77],
       [67, 48, 98, 45, 82, 51,  7, 18, 87, 87, 26, 20],
       [ 3,  8, 59, 19, 37, 73, 92, 28, 64, 55, 83, 36],
       [31, 69, 30, 16, 76,  3, 93, 92, 77, 16, 12, 43],
       [12, 21,  5, 78, 32, 50, 19, 37, 96, 18, 22, 54]], dtype=int32)

### reshape() :
- it is used to reshape the array
- Means it can convert 1D array into 2D , 3D and nD arrays without changing the elements

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

reshaped = arr.reshape(3,3)
print(reshaped)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [25]:
b = np.random.randint(10,20,(5,4))
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [26]:
type(b)

numpy.ndarray

## Indexing And Slicing In Numpy Matrix :

In [27]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

### Indexing : 

In [29]:
b[0] # forward indexing

array([18, 16, 19, 17], dtype=int32)

In [30]:
b[1]

array([13, 11, 11, 18], dtype=int32)

In [31]:
b[4]

array([15, 19, 17, 15], dtype=int32)

In [32]:
b[-1] # backward indexing 

array([15, 19, 17, 15], dtype=int32)

In [33]:
b[-2]

array([14, 14, 14, 18], dtype=int32)

In [34]:
b[-5]

array([18, 16, 19, 17], dtype=int32)

### Slicing :

In [36]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [37]:
b[:]

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [38]:
b[1:2] # forward slicing

array([[13, 11, 11, 18]], dtype=int32)

In [39]:
b[0:2]

array([[18, 16, 19, 17],
       [13, 11, 11, 18]], dtype=int32)

In [40]:
b[1:3]

array([[13, 11, 11, 18],
       [15, 18, 14, 16]], dtype=int32)

In [41]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [42]:
b[1,2]

np.int32(11)

In [43]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [44]:
b[1,3]

np.int32(18)

In [45]:
b[1,-1]

np.int32(18)

In [46]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [47]:
b[2:3]

array([[15, 18, 14, 16]], dtype=int32)

In [48]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [49]:
b[0:-2]

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16]], dtype=int32)

In [50]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [51]:
b[0:2]

array([[18, 16, 19, 17],
       [13, 11, 11, 18]], dtype=int32)

In [52]:
b[2:4]

array([[15, 18, 14, 16],
       [14, 14, 14, 18]], dtype=int32)

In [53]:
b[-5:-3] # backward slicing

array([[18, 16, 19, 17],
       [13, 11, 11, 18]], dtype=int32)

In [54]:
b[-4:2]

array([[13, 11, 11, 18]], dtype=int32)

In [55]:
np.random.randint(10,20,(4,4))

array([[11, 18, 10, 14],
       [19, 19, 13, 16],
       [14, 12, 15, 17],
       [18, 18, 10, 18]], dtype=int32)

In [56]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

In [57]:
b[-4,-2]

np.int32(11)

In [58]:
b

array([[18, 16, 19, 17],
       [13, 11, 11, 18],
       [15, 18, 14, 16],
       [14, 14, 14, 18],
       [15, 19, 17, 15]], dtype=int32)

# NumPy Operations :

In [59]:
a = np.random.randint(10,20,10)
a

array([10, 13, 14, 11, 14, 13, 18, 14, 15, 13], dtype=int32)

In [60]:
id(a)

2150776392368

In [63]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [64]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[47, 26,  0, 36, 95, 67, 11, 14, 71, 99],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58],
       [52, 23, 24, 25, 97, 76, 52, 76, 40, 47],
       [73, 40,  8, 53, 59, 69, 82, 82, 45, 56],
       [20, 34, 66, 14, 36, 96, 50, 80, 34, 90]], dtype=int32)

In [65]:
arr

array([0, 1, 2, 3, 4, 5])

In [66]:
arr[:4]

array([0, 1, 2, 3])

In [67]:
arr2[:]

array([[47, 26,  0, 36, 95, 67, 11, 14, 71, 99],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58],
       [52, 23, 24, 25, 97, 76, 52, 76, 40, 47],
       [73, 40,  8, 53, 59, 69, 82, 82, 45, 56],
       [20, 34, 66, 14, 36, 96, 50, 80, 34, 90]], dtype=int32)

In [68]:
arr2[0:5]

array([[47, 26,  0, 36, 95, 67, 11, 14, 71, 99],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14]], dtype=int32)

In [69]:
arr2

array([[47, 26,  0, 36, 95, 67, 11, 14, 71, 99],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58],
       [52, 23, 24, 25, 97, 76, 52, 76, 40, 47],
       [73, 40,  8, 53, 59, 69, 82, 82, 45, 56],
       [20, 34, 66, 14, 36, 96, 50, 80, 34, 90]], dtype=int32)

In [70]:
arr2[2,5]

np.int32(99)

In [71]:
arr2[2,6]  # show the element whose postion index 2 raw and index 6 column

np.int32(86)

In [72]:
arr2[1,4]

np.int32(67)

In [73]:
arr2[-5,5] 

np.int32(85)

In [74]:
arr2

array([[47, 26,  0, 36, 95, 67, 11, 14, 71, 99],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58],
       [52, 23, 24, 25, 97, 76, 52, 76, 40, 47],
       [73, 40,  8, 53, 59, 69, 82, 82, 45, 56],
       [20, 34, 66, 14, 36, 96, 50, 80, 34, 90]], dtype=int32)

In [75]:
arr2[::-1]  # reversed raws : the raws who was at last, now present at first

array([[20, 34, 66, 14, 36, 96, 50, 80, 34, 90],
       [73, 40,  8, 53, 59, 69, 82, 82, 45, 56],
       [52, 23, 24, 25, 97, 76, 52, 76, 40, 47],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [47, 26,  0, 36, 95, 67, 11, 14, 71, 99]], dtype=int32)

In [76]:
arr2[::-2] # backward slicing with step -2

array([[20, 34, 66, 14, 36, 96, 50, 80, 34, 90],
       [52, 23, 24, 25, 97, 76, 52, 76, 40, 47],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63]], dtype=int32)

In [77]:
arr2[::-3]

array([[20, 34, 66, 14, 36, 96, 50, 80, 34, 90],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [47, 26,  0, 36, 95, 67, 11, 14, 71, 99]], dtype=int32)

In [78]:
arr2

array([[47, 26,  0, 36, 95, 67, 11, 14, 71, 99],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58],
       [52, 23, 24, 25, 97, 76, 52, 76, 40, 47],
       [73, 40,  8, 53, 59, 69, 82, 82, 45, 56],
       [20, 34, 66, 14, 36, 96, 50, 80, 34, 90]], dtype=int32)

In [79]:
arr2[:-3]

array([[47, 26,  0, 36, 95, 67, 11, 14, 71, 99],
       [15, 38, 33, 77, 67, 70, 71, 74, 47, 63],
       [58, 77,  5, 12, 15, 99, 86, 67, 62, 55],
       [57, 54, 87, 93, 48, 42, 71, 88, 20, 67],
       [66, 57, 57, 63, 77, 71, 48, 55, 46, 14],
       [55, 71, 14, 26, 88, 85, 39, 97, 70, 95],
       [42, 44, 28, 22,  1, 83, 70, 53, 13, 58]], dtype=int32)

In [80]:
arr

array([0, 1, 2, 3, 4, 5])

In [81]:
arr.max() # give maximum value 

np.int64(5)

In [82]:
arr.min() # give minimum value

np.int64(0)

In [83]:
arr.mean() # average of the elements((0+1+2+3+4+5)/6)

np.float64(2.5)

In [85]:
arr.median() # median is a function in the NumPy module, not an attribute of ndarray

AttributeError: 'numpy.ndarray' object has no attribute 'median'

#### correct way of calling .median() :

In [86]:
import numpy as np

ar = np.array([1,2,3,6,9,4]) # numpy creation
median = np.median(ar) # median() is function of numpy
print(f"Here is a Median of Array:{ar} is {median}")

Here is a Median of Array:[1 2 3 6 9 4] is 3.5


#### Sorting :

In [89]:
unsorted_arr = np.array([5,8,3,2,0,3])
print("unsorted array :",unsorted_arr)
unsorted_arr1 = np.random.randint(0,8,6)
print("unsortd array1 :",unsorted_arr1)

sorted_arr = np.sort(unsorted_arr)
print('sorted array :',sorted_arr)

sorted_arr1 = np.sort(unsorted_arr1)
print("sorted array1 :",sorted_arr1)

unsorted array : [5 8 3 2 0 3]
unsortd array1 : [1 3 7 3 0 0]
sorted array : [0 2 3 3 5 8]
sorted array1 : [0 0 1 3 3 7]


In [92]:
# 2D array sorting
arr_2d_unsorted = np.random.randint(0,10,(3,3))

print("sorted 2D array :",np.sort(arr_2d_unsorted,axis=0)) # it sort column wise

sorted 2D array : [[0 0 2]
 [1 8 2]
 [9 9 6]]
